Feat new html rendering
tophat/RichTextView pull request #224
Opened 2022-02-25 19:28 UTC by maicon-brauwers

## Description

## DevQA

### DevQA Prep

- Run `pod install`
- Test `RichTextView` to ensure that it passes (unit and UI tests)
- Navigate to the `Example` project in the root `Example` folder and run the app
- Ensure that everything in the `Example` app looks visually correct

### DevQA Steps

### Comments

2022-02-25 20:57 UTC, maicon-brauwers commented on Package.swift
> +        .package(name: "SwiftRichString", url: "https://github.com/tophatmonocle/SwiftRichString", .branch("master"))
Pointing to our fork given that we'll need to fix some bugs on the RichString lib

2022-02-25 20:58 UTC, maicon-brauwers commented on Source/HTML Rendering/DynamicAttributesResolver.swift
> +class DynamicAttributesResolver: XMLDynamicAttributesResolver {
This class is a delegate that handles unknown tags and custom attributes.

2022-02-25 20:59 UTC, maicon-brauwers commented on Source/HTML Rendering/HTMLRenderer.swift
> +class HTMLRenderer {
Core class responsible for the rendering; it generates the styles if needed and then call the SwiftRichString set:style method

2022-02-25 20:59 UTC, maicon-brauwers commented on Source/HTML Rendering/HTMLStyleBuilder.swift
> +struct HTMLStyleBuilder {
This builds the styles. Not all required styles are here - will work on it on a follow up ticket.

2022-02-25 21:00 UTC, maicon-brauwers commented on Source/RichTextView.swift
> +                shouldUseOptimizedHTMLParsing: Bool = false,
Parameters to control the version of rendering we should be using

2022-02-25 21:00 UTC, maicon-brauwers commented on Source/Text Parsing/RichTextParser.swift
> +            let specialDataSubstring: String = specialDataTypesString.string[
To disambiguate

2022-02-25 21:00 UTC, maicon-brauwers commented on Source/Text Parsing/RichTextParser.swift
> +    private func getRichTextWithHTMLAndMarkdownHandledV2(
V2 shorter method

2022-02-28 14:57 UTC, Noobish1 requested changes
Just a few comments/questions

2022-02-28 14:57 UTC, Noobish1 commented on Source/HTML Rendering/DynamicAttributesResolver.swift
> +                if value.starts(with: "color: rgb(") {
will this be changed later?

2022-02-28 15:58 UTC, maicon-brauwers commented on Source/HTML Rendering/DynamicAttributesResolver.swift
> +                if value.starts(with: "color: rgb(") {
Yes, I will change it later on follow up tickets.

2022-02-28 15:58 UTC, maicon-brauwers commented on Source/HTML Rendering/HTMLRenderer.swift
> +    func renderHTML(html: String, styleParams: HTMLStyleParams) -> NSAttributedString {
Nice, good suggestion, I will change.

2022-02-28 16:00 UTC, maicon-brauwers commented on Source/HTML Rendering/HTMLStyleBuilder.swift
> +            $0.backColor = Color(red: 249/255, green: 249/255, blue: 249/255, alpha: 1.0)
Yes, this is true. The PR really captures work in progress, and we will complete it on follow up tickets. 

But you are right - we probably should add color parameters to the `HTMLStyleParams` struct.
Or move the responsibility of build styles to the application instead of the framework.

2022-02-28 21:54 UTC, Noobish1 approved these changes
LGTM

2022-03-01 14:05 UTC, merged